name: cargo build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Enter nix shell
      run: nix develop
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
